# Generated by Django 6.0.1 on 2026-03-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DivisaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes', to='protocolos.protocolo')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('protocolo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_min', models.IntegerField(default=10)),
                ('tempo_max', models.IntegerField(default=40)),
                ('frequencia', models.CharField(default='Todos os dias', max_length=100)),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardio', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticoes_min', models.IntegerField(blank=True, null=True)),
                ('repeticoes_max', models.IntegerField(blank=True, null=True)),
                ('tempo_execucao', models.IntegerField(blank=True, help_text='Tempo em segundos', null=True)),
                ('tipo_execucao', models.CharField(choices=[('reps', 'Repetições'), ('tempo', 'Tempo')], default='reps', max_length=10)),
                ('carga', models.FloatField(blank=True, null=True)),
                ('tempo_descanso', models.IntegerField(blank=True, help_text='Tempo de descanso em segundos', null=True)),
                ('ordem', models.IntegerField()),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='protocolos.divisaotreino')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolos.exercicio')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
